import jwt from 'jsonwebtoken';
const { sign, verify } = jwt;
import { injectable, inject } from 'tsyringe';
import { hash, compare } from 'bcryptjs';
import { NODE_ENV, SECRET_KEY } from '@config/env';
import { HttpException } from '@exceptions/httpException';
import { DataStoredInToken, TokenData } from '@interfaces/auth.interface';
import { User } from '@entities/user.entity';
import { UsersRepository } from '@repositories/users.repository';
import type { IUsersRepository } from '@repositories/users.repository';
import { CaptchaService } from './captcha.service';

@injectable()
export class AuthService {
  constructor(
    @inject(UsersRepository) private usersRepository: IUsersRepository,
    @inject(CaptchaService) private captchaService: CaptchaService
  ) {}

  private createAccessToken(user: User): TokenData {
    if (!SECRET_KEY) throw new Error('SECRET_KEY is not defined');
    if (!user.id) throw new Error('User id is undefined');

    const dataStoredInToken: DataStoredInToken = { id: user.id };
    const expiresIn = 15 * 60; // 15 minutes
    const token = sign(dataStoredInToken, SECRET_KEY, { expiresIn });
    return { expiresIn, token };
  }

  private createRefreshToken(user: User): TokenData {
    if (!SECRET_KEY) throw new Error('SECRET_KEY is not defined');
    if (!user.id) throw new Error('User id is undefined');

    const dataStoredInToken: DataStoredInToken = { id: user.id };
    const expiresIn = 7 * 24 * 60 * 60; // 7 days
    const token = sign(dataStoredInToken, SECRET_KEY, { expiresIn });
    return { expiresIn, token };
  }

  public createCookie(tokenData: TokenData, name: string = 'Authorization'): string {
    return `${name}=${tokenData.token}; HttpOnly; Max-Age=${
      tokenData.expiresIn
    }; Path=/; SameSite=Lax;${NODE_ENV === 'production' ? ' Secure;' : ''}`;
  }

  public async loginWithWallet(walletAddress: string, captchaToken?: string): Promise<{
    accessTokenCookie: string;
    refreshTokenCookie: string;
    user: User;
  }> {
    // Verify CAPTCHA
    if (NODE_ENV === 'production') {
      if (!captchaToken) {
        throw new HttpException(400, 'Captcha token is required');
      }
      const isCaptchaValid = await this.captchaService.verifyToken(captchaToken);
      if (!isCaptchaValid) {
        throw new HttpException(400, 'Invalid CAPTCHA');
      }
    }

    let user = await this.usersRepository.findByWalletAddress(walletAddress);

    if (!user) {
      console.log(`[AuthService] User not found for wallet ${walletAddress}. Creating new user.`);
      user = await User.create({ walletAddress });
      // We need to save the user first to get an ID if it's generated by DB, 
      // but here User.create generates ID.
    }

    const accessTokenData = this.createAccessToken(user);
    const refreshTokenData = this.createRefreshToken(user);

    // Hash refresh token and save to user
    const hashedRefreshToken = await hash(refreshTokenData.token, 10);
    
    user.setRefreshToken(hashedRefreshToken);
    
    if (await this.usersRepository.findById(user.id)) {
        await this.usersRepository.update(user.id, user);
    } else {
        await this.usersRepository.save(user);
    }

    const accessTokenCookie = this.createCookie(accessTokenData, 'Authorization');
    const refreshTokenCookie = this.createCookie(refreshTokenData, 'RefreshToken');

    return { accessTokenCookie, refreshTokenCookie, user };
  }

  public async logout(user: User): Promise<void> {
    (user as any)._refreshToken = undefined;
    await this.usersRepository.update(user.id, user);
  }

  public async refresh(refreshToken: string): Promise<{ accessTokenCookie: string; refreshTokenCookie: string; user: User }> {
    if (!SECRET_KEY) throw new Error('SECRET_KEY is not defined');

    try {
      const verificationResponse = verify(refreshToken, SECRET_KEY) as DataStoredInToken;
      const userId = verificationResponse.id;
      
      const user = await this.usersRepository.findByIdWithToken(userId as string);
      
      if (!user) {
         throw new HttpException(401, 'User not found');
      }

      // Check if user has a refresh token stored
      // Accessing private _refreshToken via getter if exists, or casting
      const storedRefreshToken = (user as any)._refreshToken;
      
      if (!storedRefreshToken) {
          throw new HttpException(401, 'No refresh token found');
      }

      const isMatching = await compare(refreshToken, storedRefreshToken);
      if (!isMatching) {
        throw new HttpException(401, 'Invalid refresh token');
      }

      // Rotate tokens
      const accessTokenData = this.createAccessToken(user);
      const newRefreshTokenData = this.createRefreshToken(user);
      
      const hashedRefreshToken = await hash(newRefreshTokenData.token, 10);
      (user as any)._refreshToken = hashedRefreshToken;
      await this.usersRepository.update(user.id, user);

      const accessTokenCookie = this.createCookie(accessTokenData, 'Authorization');
      const refreshTokenCookie = this.createCookie(newRefreshTokenData, 'RefreshToken');

      return { accessTokenCookie, refreshTokenCookie, user };

    } catch (error) {
      throw new HttpException(401, 'Invalid refresh token');
    }
  }
}
